# ------------------------------------------------------------------------------
# Configuration unique to this application.  Will be loaded as the `config`
# variable of the Application class.
# ------------------------------------------------------------------------------

config: {}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grimoire?useLegacyDatetimeCode=false&serverTimezone=America/Denver
    username: grimoire
    password: grimoire1234
    initialization-mode: always